"""
LMIS SQLAlchemy Async Base
==========================
Abstract base class for all ORM models, providing:
- UUID primary key (server-side default via gen_random_uuid())
- created_at timestamp (non-nullable, auto-set on INSERT)
- updated_at timestamp (non-nullable, auto-updated on every UPDATE via trigger)
"""
from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """DeclarativeBase for all LMIS ORM models."""

    pass


class TimestampMixin:
    """Mixin that adds created_at and updated_at auto-timestamps."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        doc="Timestamp when the record was first inserted",
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        doc="Timestamp of the last update; auto-refreshed on every UPDATE",
    )


class UUIDBase(Base, TimestampMixin):
    """Abstract base with UUID PK + automatic timestamps.

    Subclass this for every LMIS table. Example::

        class MyModel(UUIDBase):
            __tablename__ = "my_table"
            name: Mapped[str]
    """

    __abstract__ = True

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        default=uuid.uuid4,
        doc="Primary key — UUID v4, generated by the application or PostgreSQL",
    )
